### ISSUE TITLE
Update GIS example models for Cell API changes

### ISSUE THREAD

**Issue by EwoutH** [projectmesa/mesa-examples#326]
### Problem
Three GIS example models in Mesa-examples are failing due to breaking changes introduced in https://github.com/mesa/mesa-geo/pull/299, which added new keyword arguments (`rowcol`, `xy`) to the `Cell.__init__()` method.

**Failing models:**
- `gis/urban_growth` - `UrbanCell`
- `gis/rainfall` - `LakeCell`  
- `gis/population` - `UgandaCell`

**Error:**
```
TypeError: <CustomCell>.__init__() got an unexpected keyword argument 'rowcol'
```

### Root cause
The updated `Cell.__init__()` in mesa-geo now accepts keyword-only arguments `rowcol` and `xy`:

```python
def __init__(self, model, pos=None, indices=None, *, rowcol=None, xy=None):
```

Custom `Cell` subclasses in the example models don't accept these arguments, causing instantiation to fail when `RasterLayer._initialize_cells()` tries to create cells.

### Additional considerations
While fixing the signatures, we might update the models to use the new `cell.rowcol` property instead of the deprecated `cell.indices` where applicable.

**Comment by Harshini2411** [comment]
@EwoutH Hi, I'd like to work on this fix. I'll update the __init__ signatures for UrbanCell, LakeCell, and UgandaCell to accept the new rowcol and xy kwargs.
